-- Logs begin at Thu 2022-10-20 05:53:27 IST, end at Thu 2022-10-20 05:53:31 IST. --
Oct 20 05:53:28 datacore-PowerEdge-R740 sudo[1419879]: pam_unix(sudo:session): session closed for user root
Oct 20 05:53:28 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.083s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:28 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:28 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:28 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:28 datacore-PowerEdge-R740 sudo[1419929]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Oct 20 05:53:28 datacore-PowerEdge-R740 sudo[1419929]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 20 05:53:29 datacore-PowerEdge-R740 sudo[1419929]: pam_unix(sudo:session): session closed for user root
Oct 20 05:53:29 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 1.011s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:29 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:29 datacore-PowerEdge-R740 sudo[1420055]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 20 05:53:29 datacore-PowerEdge-R740 sudo[1420055]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 20 05:53:29 datacore-PowerEdge-R740 sudo[1420055]: pam_unix(sudo:session): session closed for user root
Oct 20 05:53:29 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.663s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:29 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:30 datacore-PowerEdge-R740 sudo[1420109]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 20 05:53:30 datacore-PowerEdge-R740 sudo[1420109]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 20 05:53:30 datacore-PowerEdge-R740 sudo[1420109]: pam_unix(sudo:session): session closed for user root
Oct 20 05:53:30 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.633s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:30 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:30 datacore-PowerEdge-R740 sudo[1420113]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 20 05:53:30 datacore-PowerEdge-R740 sudo[1420113]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 20 05:53:31 datacore-PowerEdge-R740 sudo[1420113]: pam_unix(sudo:session): session closed for user root
Oct 20 05:53:31 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.640s {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 20 05:53:31 datacore-PowerEdge-R740 cinder-volume[1419799]: DEBUG oslo_concurrency.processutils [None req-84c7cdfe-8f16-472f-903c-05934780b07c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1419799) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 20 05:53:31 datacore-PowerEdge-R740 sudo[1420121]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 20 05:53:31 datacore-PowerEdge-R740 sudo[1420121]: pam_unix(sudo:session): session opened for user root by (uid=0)
