-- Logs begin at Fri 2022-11-04 02:43:00 IST, end at Fri 2022-11-04 02:43:10 IST. --
Nov 04 02:43:01 datacore-PowerEdge-R740 sudo[210577]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:01 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings -o name stack-volumes-lvmdriver-1" returned: 0 in 1.096s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:01 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:01 datacore-PowerEdge-R740 sudo[210607]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Nov 04 02:43:01 datacore-PowerEdge-R740 sudo[210607]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:02 datacore-PowerEdge-R740 sudo[210607]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:02 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.109s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:02 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:02 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.029s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:02 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:02 datacore-PowerEdge-R740 sudo[210646]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Nov 04 02:43:02 datacore-PowerEdge-R740 sudo[210646]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:03 datacore-PowerEdge-R740 sudo[210646]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:03 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.066s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:03 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:03 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.015s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:03 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:03 datacore-PowerEdge-R740 sudo[210701]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Nov 04 02:43:03 datacore-PowerEdge-R740 sudo[210701]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:04 datacore-PowerEdge-R740 sudo[210701]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:04 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 1.007s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:04 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:04 datacore-PowerEdge-R740 sudo[210769]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Nov 04 02:43:04 datacore-PowerEdge-R740 sudo[210769]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:05 datacore-PowerEdge-R740 sudo[210769]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:05 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.836s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:05 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:05 datacore-PowerEdge-R740 sudo[210898]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Nov 04 02:43:05 datacore-PowerEdge-R740 sudo[210898]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210898]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:06 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.646s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:06 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210911]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210911]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210911]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:06 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.669s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:06 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210915]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Nov 04 02:43:06 datacore-PowerEdge-R740 sudo[210915]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:07 datacore-PowerEdge-R740 sudo[210915]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:07 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.664s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:07 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:07 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:07 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:07 datacore-PowerEdge-R740 sudo[210924]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Nov 04 02:43:07 datacore-PowerEdge-R740 sudo[210924]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[210924]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.637s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: INFO cinder.volume.drivers.lvm [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.015s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[211102]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[211102]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[211102]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.641s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG cinder.volume.drivers.lvm [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Updating volume stats {{(pid=210573) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Nov 04 02:43:08 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[211109]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Nov 04 02:43:08 datacore-PowerEdge-R740 sudo[211109]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 04 02:43:09 datacore-PowerEdge-R740 sudo[211109]: pam_unix(sudo:session): session closed for user root
Nov 04 02:43:09 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.614s {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Nov 04 02:43:09 datacore-PowerEdge-R740 cinder-volume[210573]: DEBUG oslo_concurrency.processutils [None req-86166fbd-75d9-4981-9fab-aee21df4dd23 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=210573) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Nov 04 02:43:09 datacore-PowerEdge-R740 sudo[211117]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Nov 04 02:43:09 datacore-PowerEdge-R740 sudo[211117]: pam_unix(sudo:session): session opened for user root by (uid=0)
