-- Logs begin at Tue 2022-09-20 12:29:29 IST, end at Tue 2022-09-20 12:29:43 IST. --
Sep 20 12:29:30 datacore-PowerEdge-R740 sudo[2258297]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:30 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings -o name stack-volumes-lvmdriver-1" returned: 0 in 1.185s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:30 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:30 datacore-PowerEdge-R740 sudo[2258325]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:30 datacore-PowerEdge-R740 sudo[2258325]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:31 datacore-PowerEdge-R740 sudo[2258325]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:31 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.101s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:31 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:31 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:31 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:31 datacore-PowerEdge-R740 sudo[2258389]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:31 datacore-PowerEdge-R740 sudo[2258389]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:32 datacore-PowerEdge-R740 sudo[2258389]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:32 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.019s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:32 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:32 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:32 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:32 datacore-PowerEdge-R740 sudo[2258456]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Sep 20 12:29:32 datacore-PowerEdge-R740 sudo[2258456]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:33 datacore-PowerEdge-R740 sudo[2258456]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:33 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.881s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:33 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:33 datacore-PowerEdge-R740 sudo[2258573]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:29:33 datacore-PowerEdge-R740 sudo[2258573]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:34 datacore-PowerEdge-R740 sudo[2258573]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:34 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.705s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:34 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:34 datacore-PowerEdge-R740 sudo[2258617]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:29:34 datacore-PowerEdge-R740 sudo[2258617]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258617]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:35 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.689s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:35 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258623]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258623]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258623]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:35 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.707s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:35 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258640]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:35 datacore-PowerEdge-R740 sudo[2258640]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:36 datacore-PowerEdge-R740 sudo[2258640]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:36 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.622s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:36 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:36 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:36 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:36 datacore-PowerEdge-R740 sudo[2258647]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:36 datacore-PowerEdge-R740 sudo[2258647]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258647]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.608s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.volume.drivers.lvm [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258652]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258652]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258652]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.642s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.volume.drivers.lvm [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Updating volume stats {{(pid=2258290) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:29:37 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258667]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:29:37 datacore-PowerEdge-R740 sudo[2258667]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:38 datacore-PowerEdge-R740 sudo[2258667]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:38 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.646s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:38 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:38 datacore-PowerEdge-R740 sudo[2258671]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:29:38 datacore-PowerEdge-R740 sudo[2258671]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258671]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:39 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.647s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:39 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258678]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258678]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:39 datacore-PowerEdge-R740 cinder-volume[2258081]: DEBUG dbcounter [-] [2258081] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2258081) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258678]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:39 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.634s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:39 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258692]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:29:39 datacore-PowerEdge-R740 sudo[2258692]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:40 datacore-PowerEdge-R740 sudo[2258692]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.644s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.volume.driver [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Driver hasn't implemented _init_vendor_properties()
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.volume.driver [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2258290) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:811}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_db.sqlalchemy.engines [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2258290) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG dbcounter [-] [2258290] Writer thread running {{(pid=2258290) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.db.sqlalchemy.api [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Building query based on filter {{(pid=2258290) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3378}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.image.image_utils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2258290) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.volume.drivers.lvm [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Updating volume stats {{(pid=2258290) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:40 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.keymgr.migration [None req-8a51a10d-f461-4a0c-bf33-ee8fc1115ab8 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 20 12:29:40 datacore-PowerEdge-R740 sudo[2258699]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:29:40 datacore-PowerEdge-R740 sudo[2258699]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258699]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:41 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.657s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:41 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258709]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258709]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258709]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:41 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.662s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:41 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258730]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:29:41 datacore-PowerEdge-R740 sudo[2258730]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:42 datacore-PowerEdge-R740 sudo[2258730]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:42 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.635s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:42 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:42 datacore-PowerEdge-R740 sudo[2258737]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:29:42 datacore-PowerEdge-R740 sudo[2258737]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:29:43 datacore-PowerEdge-R740 sudo[2258737]: pam_unix(sudo:session): session closed for user root
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.669s {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.manager [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Notifying Schedulers of capabilities ... {{(pid=2258290) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.volume.manager [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Driver initialization completed successfully.
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.manager [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Initiating service 2 cleanup
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.manager [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Service 2 cleanup completed.
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.service [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Creating RPC server for service cinder-volume {{(pid=2258290) start /opt/stack/cinder/cinder/service.py:231}}
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.service [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2258290) start /opt/stack/cinder/cinder/service.py:237}}
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: INFO cinder.volume.manager [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG cinder.volume.drivers.lvm [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Updating volume stats {{(pid=2258290) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:29:43 datacore-PowerEdge-R740 cinder-volume[2258290]: DEBUG oslo_concurrency.processutils [None req-edef312f-dd70-405b-8d71-c0c260f2e8eb None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2258290) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:29:43 datacore-PowerEdge-R740 sudo[2258755]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:29:43 datacore-PowerEdge-R740 sudo[2258755]: pam_unix(sudo:session): session opened for user root by (uid=0)
